export type Batch = {
  product_source?: string;
  species?: string;
  FAO_Area?: string;
  location?: string;
  fishery: string;
  harvest_method?: string;
  ingredients_en?: string;
  ingredients_fr?: string;
  best_before_date?: string;
  lot_number?: string;
  batch_number: string;
  url?: string;
  product?: string;
  fishery_name: string;
  img?: string;
};

export const batches: Batch[] = [
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild chinook salmon (Oncorhynchus tshawytscha), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon quinnat sauvage (Oncorhynchus tshawytscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '523642',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Chinook Salmon',
    img: '/candied-chinook-salmon.jpg',
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild chinook salmon (Oncorhynchus tshawytscha), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon quinnat sauvage (Oncorhynchus tshawytscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '623641',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Chinook Salmon',
    img: '/candied-chinook-salmon.jpg',
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild chinook salmon (Oncorhynchus tshawytscha), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon quinnat sauvage (Oncorhynchus tshawytscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '624041',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Chinook Salmon',
    img: '/candied-chinook-salmon.jpg',
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild chinook salmon (Oncorhynchus tshawytscha), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon quinnat sauvage (Oncorhynchus tshawytscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: '2026, February 26',
    lot_number: undefined,
    batch_number: '523942',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Chinook Salmon',
    img: '/candied-chinook-salmon.jpg',
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild chinook salmon (Oncorhynchus tshawytscha), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon quinnat sauvage (Oncorhynchus tshawytscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '524242',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Chinook Salmon',
    img: '/candied-chinook-salmon.jpg',
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild chinook salmon (Oncorhynchus tshawytscha), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon quinnat sauvage (Oncorhynchus tshawytscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '624341',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Chinook Salmon',
    img: '/candied-chinook-salmon.jpg',
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild chinook salmon (Oncorhynchus tshawytscha), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon quinnat sauvage (Oncorhynchus tshawytscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '624342',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Chinook Salmon',
    img: '/candied-chinook-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '519841',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '520042',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '619842',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '619942',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '619943',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '620042',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '519442',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '519841',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: '2026, May 13',
    lot_number: undefined,
    batch_number: '531841',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '619442',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild coho salmon (Oncorhynchus kisutch), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon coho sauvage (Oncorhynchus kisutch), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '619841',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Candied Wild Coho Salmon',
    img: '/candied-coho-salmon.jpg',
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Seafoam Seafoods',
    fishery: 'Pacheedaht First Nation',
    harvest_method: undefined,
    ingredients_en: 'wild keta salmon (Oncorhynchus keta), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon keta sauvage (Oncorhynchus keta), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '520642',
    fishery_name: 'Seafoam Seafoods',
    url: 'https://authenticindigenousseafood.ca/fisheries/seafoam-seafoods/',
    product: 'Candied Wild Keta Salmon',
    img: '/candied-keta-salmon.jpg',
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Seafoam Seafoods',
    fishery: 'Pacheedaht First Nation',
    harvest_method: undefined,
    ingredients_en: 'wild keta salmon (Oncorhynchus keta), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon keta sauvage (Oncorhynchus keta), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: '2026, January 25',
    lot_number: undefined,
    batch_number: '520741',
    fishery_name: 'Seafoam Seafoods',
    url: 'https://authenticindigenousseafood.ca/fisheries/seafoam-seafoods/',
    product: 'Candied Wild Keta Salmon',
    img: '/candied-keta-salmon.jpg',
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Seafoam Seafoods',
    fishery: 'Pacheedaht First Nation',
    harvest_method: undefined,
    ingredients_en: 'wild keta salmon (Oncorhynchus keta), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon keta sauvage (Oncorhynchus keta), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '520841',
    fishery_name: 'Seafoam Seafoods',
    url: 'https://authenticindigenousseafood.ca/fisheries/seafoam-seafoods/',
    product: 'Candied Wild Keta Salmon',
    img: '/candied-keta-salmon.jpg',
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Seafoam Seafoods',
    fishery: 'Pacheedaht First Nation',
    harvest_method: undefined,
    ingredients_en: 'wild keta salmon (Oncorhynchus keta), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon keta sauvage (Oncorhynchus keta), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '620641',
    fishery_name: 'Seafoam Seafoods',
    url: 'https://authenticindigenousseafood.ca/fisheries/seafoam-seafoods/',
    product: 'Candied Wild Keta Salmon',
    img: '/candied-keta-salmon.jpg',
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Seafoam Seafoods',
    fishery: 'Pacheedaht First Nation',
    harvest_method: undefined,
    ingredients_en: 'wild keta salmon (Oncorhynchus keta), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon keta sauvage (Oncorhynchus keta), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '620642',
    fishery_name: 'Seafoam Seafoods',
    url: 'https://authenticindigenousseafood.ca/fisheries/seafoam-seafoods/',
    product: 'Candied Wild Keta Salmon',
    img: '/candied-keta-salmon.jpg',
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Seafoam Seafoods',
    fishery: 'Pacheedaht First Nation',
    harvest_method: undefined,
    ingredients_en: 'wild keta salmon (Oncorhynchus keta), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon keta sauvage (Oncorhynchus keta), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '620741',
    fishery_name: 'Seafoam Seafoods',
    url: 'https://authenticindigenousseafood.ca/fisheries/seafoam-seafoods/',
    product: 'Candied Wild Keta Salmon',
    img: '/candied-keta-salmon.jpg',
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Seafoam Seafoods',
    fishery: 'Pacheedaht First Nation',
    harvest_method: undefined,
    ingredients_en: 'wild keta salmon (Oncorhynchus keta), sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon keta sauvage (Oncorhynchus keta), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '620742',
    fishery_name: 'Seafoam Seafoods',
    url: 'https://authenticindigenousseafood.ca/fisheries/seafoam-seafoods/',
    product: 'Candied Wild Keta Salmon',
    img: '/candied-keta-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '504441',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '68 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '604441',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '69 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '604342',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '70 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '504341',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '71 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '604742',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '72 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '604741',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '73 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '604641',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '74 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '504642',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '75 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: '2026, April 30',
    lot_number: undefined,
    batch_number: '530441',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '76 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '504541',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Pink Salmon',
    species: 'Oncorhynchus gorbuscha',
    FAO_Area: '77 – Pacific Ocean',
    location: 'Campbell River, British Colimbia - Canada',
    fishery: 'We Wai Kai and Wei Wai Kum First Nations',
    harvest_method: 'ESSR',
    ingredients_en: 'wild pink salmon (Oncorhynchus gorbuscha) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus gorbuscha), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '604541',
    fishery_name: 'We Wai Kai and Wei Wai Kum Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/a-tlegay-fisheries/',
    product: 'Candied Wild Pink Salmon',
    img: '/candied-pink-salmon.jpg',
  },
  {
    product_source: 'Wild Sockeye Salmon',
    species: 'Oncorhynchus nerka',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Lax an Zok, Meziadin Junction Fishway and the Nass River, British Columbia – Canada',
    fishery: 'Gitanyow First Nation',
    harvest_method: 'Dipnet fishery',
    ingredients_en: 'wild sockeye salmon (Oncorhynchus nerka) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus nerka), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '626442',
    fishery_name: 'Gitanyow Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/gitanyow-fisheries/',
    product: 'Candied Wild Sockeye Salmon',
    img: '/candied-sockeye-salmon.jpg',
  },
  {
    product_source: 'Wild Sockeye Salmon',
    species: 'Oncorhynchus nerka',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Lax an Zok, Meziadin Junction Fishway and the Nass River, British Columbia – Canada',
    fishery: 'Gitanyow First Nation',
    harvest_method: 'Dipnet fishery',
    ingredients_en: 'wild sockeye salmon (Oncorhynchus nerka) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus nerka), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: '2025, February 24',
    lot_number: undefined,
    batch_number: '623632',
    fishery_name: 'Gitanyow Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/gitanyow-fisheries/',
    product: 'Candied Wild Sockeye Salmon',
    img: '/candied-sockeye-salmon.jpg',
  },
  {
    product_source: 'Wild Sockeye Salmon',
    species: 'Oncorhynchus nerka',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Lax an Zok, Meziadin Junction Fishway and the Nass River, British Columbia – Canada',
    fishery: 'Gitanyow First Nation',
    harvest_method: 'Dipnet fishery',
    ingredients_en: 'wild sockeye salmon (Oncorhynchus nerka) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus nerka), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '626741',
    fishery_name: 'Gitanyow Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/gitanyow-fisheries/',
    product: 'Candied Wild Sockeye Salmon',
    img: '/candied-sockeye-salmon.jpg',
  },
  {
    product_source: 'Wild Sockeye Salmon',
    species: 'Oncorhynchus nerka',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Lax an Zok, Meziadin Junction Fishway and the Nass River, British Columbia – Canada',
    fishery: 'Gitanyow First Nation',
    harvest_method: 'Dipnet fishery',
    ingredients_en: 'wild sockeye salmon (Oncorhynchus nerka) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus nerka), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: '507431',
    fishery_name: 'Gitanyow Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/gitanyow-fisheries/',
    product: 'Candied Wild Sockeye Salmon',
    img: '/candied-sockeye-salmon.jpg',
  },
  {
    product_source: 'Wild Sockeye Salmon',
    species: 'Oncorhynchus nerka',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Lake Babine, British Columbia - Canada',
    fishery: 'Lake Babine First Nation',
    harvest_method: 'Seine fishery',
    ingredients_en: 'wild sockeye salmon (Oncorhynchus nerka) , sugar, salt, natural alder wood smoke. May contain traces of gluten or soy.',
    ingredients_fr: 'saumon rose sauvage (Oncorhynchus nerka), sucre, sel, fumée de bois d’alune naturel. Peut contenir des traces de gluten ou de soja.',
    best_before_date: '2025, October 24',
    lot_number: undefined,
    batch_number: '511642',
    fishery_name: 'Talok Fisheries',
    url: 'https://authenticindigenousseafood.ca/fisheries/talok-fisheries/',
    product: 'Candied Wild Sockeye Salmon',
    img: '/candied-sockeye-salmon.jpg',
  },
  {
    product_source: 'Wild Sockeye Salmon',
    species: 'Oncorhynchus nerka',
    FAO_Area: undefined,
    location: 'Okanagan, British Columbia - Canada',
    fishery: 'Syilx First Nation ',
    harvest_method: undefined,
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'OAE240914SCSSX',
    fishery_name: 'Okanagan Select',
    url: 'https://authenticindigenousseafood.ca/fisheries/okanagan-select/',
    product: 'Wild Sockeye Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240926SCCO',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Coho Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240929SCCO',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Coho Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS241002SCCO',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Coho Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Coho Salmon',
    species: 'Oncorhynchus kisutch',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS241008SCCO',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Coho Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Chehalis, Harrison, and adjacent Fraser Rivers, British Columbia - Canada',
    fishery: 'Sts’ailes and Scowlitz First Nations',
    harvest_method: undefined,
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS241115CCH',
    fishery_name: 'Harrison Select',
    url: 'https://authenticindigenousseafood.ca/fisheries/harrison-select/',
    product: 'Wild Keta Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Chehalis, Harrison, and adjacent Fraser Rivers, British Columbia - Canada',
    fishery: 'Sts’ailes and Scowlitz First Nations',
    harvest_method: undefined,
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS241121CCH',
    fishery_name: 'Harrison Select',
    url: 'https://authenticindigenousseafood.ca/fisheries/harrison-select/',
    product: 'Wild Keta Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Keta Salmon',
    species: 'Oncorhynchus keta',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Chehalis, Harrison, and adjacent Fraser Rivers, British Columbia - Canada',
    fishery: 'Sts’ailes and Scowlitz First Nations',
    harvest_method: undefined,
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240724SCCH',
    fishery_name: 'Harrison Select',
    url: 'https://authenticindigenousseafood.ca/fisheries/harrison-select/',
    product: 'Wild Keta Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '67 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240117SCSP',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Chinook Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '68 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240118SCSP',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Chinook Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '69 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240121SCSP',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Chinook Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '70 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240123SCSP',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Chinook Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '71 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240125SCSP',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Chinook Caviar',
    img: undefined,
  },
  {
    product_source: 'Wild Chinook Salmon',
    species: 'Oncorhynchus tshawytscha',
    FAO_Area: '72 – Pacific Ocean',
    location: 'Port Alberni, British Columbia – Canada',
    fishery: 'Hupačasath and Tseshaht First Nations',
    harvest_method: 'ESSR',
    ingredients_en: undefined,
    ingredients_fr: undefined,
    best_before_date: undefined,
    lot_number: undefined,
    batch_number: 'RS240126SCSP',
    fishery_name: 'Tsu-ma-uss Seafoods',
    url: 'https://www.authenticindigenousseafood.ca/fisheries/tsu-ma-uss-seafoods/',
    product: 'Wild Chinook Caviar',
    img: undefined,
  }
];
